services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: 
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker 
    working_dir: /app
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: Level2DB
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

