services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: 
      - .env
    environment:
      - DATABASE_URL
      - DATABASE_USER
      - DATABASE_PASSWORD
    working_dir: /app
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:13.1
    container_name: db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: Level2DB
    ports:
      - "5432:5432"
