services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=jdbc:postgresql://springboot_database_4imk_user:h0Oy0LhcDCR07MYHzM8aR69xMzYVVhTE@dpg-csnn7823esus73efe1k0-a/springboot_database_4imk
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    working_dir: /app
    ports:
      - 8080:8080
      - 5050:5050
    tty: true
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:13.1
    container_name: db
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
